### ISSUE TITLE
Interface method to another color?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [charlespascoe/vim-go-syntax#3]
Hi, I would love to see, in my code, when method is from interface, for example `Read`.

**Comment by charlespascoe** [comment]
Hi! Could you clarify what you mean by 'a method from an interface'? Do you mean calling a method on an interface type, or calling a method on a type that happens to conform to some interface?

In either case, this would require type information, which isn't something Vim syntax definitions have - they're purely lexical, so highlighting is based only on the text in the file.

**Comment by vitaly-zdanevich** [comment]
> Do you mean calling a method on an interface type, or calling a method on a type that happens to conform to some interface?

Both would be great.

> this would require type information

Is it possible to integrate with vim-go, gopls?

**Comment by charlespascoe** [comment]
The first one (calling a method on an interface type) would require a lot of effort - even under the assumption you can get that information about a particular function call at a given location, it would still require using something like Vim's text properties to overlay custom syntax colours, which would likely result in odd highlighting artefacts when changing neighbouring code.

Now that I think about it, the second probably isn't feasible in any tolerable fashion (calling a method on a type that happens to conform to some interface) - it would require searching all available interfaces to see if one matched the call signature, which would be extremely slow even on a fast computer, and it would need to run every time the code was changed.

Overall, I don't think either of these justify the effort required to implement them, not to mention the fact that it would be special-case code that is completely separate from the rest of the syntax highlighting.

**Comment by vitaly-zdanevich** [comment]
> it would require searching all available interfaces to see if one matched the call signature

Just saying, [vim-go](https://github.com/fatih/vim-go) can do that.

**Comment by charlespascoe** [comment]
I hadn't used the `GoImplements` command before - that's cool. It's not enough by itself to do what you're asking, unfortunately.
