### ISSUE TITLE
Was 'goto' deliberately omitted?

### ISSUE THREAD

**Issue by tazimmerman** [charlespascoe/vim-go-syntax#4]
First, thank you for this plugin, and the sheer amount of customization. For someone with low-vision, the contrast I'm able to achieve with this makes screen time far more enjoyable.

I am curious though, was `goto` deliberately omitted from the highlights? I wouldn't be surprised if it was skipped simply because it's not frequently used, but it does have its place in code.

Would it be possible to associate with a highlight group (e.g. perhaps the same as labels) by default?

**Comment by charlespascoe** [comment]
Hi @tazimmerman! Thank you, I'm glad it's been helpful to you 🙂

It was a mistake that I missed `goto` when writing the syntax highlighter; I don't use it much and so I hadn't noticed. Thanks for pointing it out - I've added it in v1.0.0 👍
